env:
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "airbnb-base"
  # - "prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
