name: lint-sources

on: push

jobs:
  lint-sources:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Node installing
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run linter
        run: make lint
